steps:
  # Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'streamlit-app'
      - '--image'
      - 'gcr.io/shared-vikas/streamlit-app:v1'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
options:
  logsBucket: 'exp-demo-1'  # Option 1: Specify a logs bucket
  # default_logs_bucket_behavior: 'REGIONAL_USER_OWNED_BUCKET'  # Option 2: Use regional user-owned bucket
  # logging: 'CLOUD_LOGGING_ONLY'  # Option 3: Use cloud logging only


