steps:
  # Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'streamlit-app'
      - '--image'
      - 'gcr.io/shared-vikas/streamlit-app:v1'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
options:
  machineType: 'N1_HIGHCPU_8'  # Optional: Customize machine type based on your requirements
  logging:
    - 'CLOUD_LOGGING_ONLY'  # Specify cloud logging only

